// -----------------------------------------------------------------------------
//      Attention: This file is generated by "yarn codegen"
//                           Do not modify by hand
//              Run "yarn codegen" to regenerate this file
// -----------------------------------------------------------------------------

import type * as ESLint from 'eslint';

export const recommended: ESLint.Linter.Config = {
    rules: {
        // {{TEMPLATE_RULE_DEFINITIONS}}
    },
};
